# Generated by Django 5.2.12 on 2026-03-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('text_file', models.FileField(blank=True, null=True, upload_to='comments/text_file')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='comments/image_file')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parent_comment', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='replies', to='comments.comment'
                )),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
