# Generated by Django 5.2.12 on 2026-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="homepage",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
